CREATE DATABASE FINANCAS;
CREATE TABLE USUARIO (ID INT PRIMARY KEY AUTO_INCREMENT, LOGIN VARCHAR(100), EMAIL VARCHAR(100), SENHA VARCHAR(100));
CREATE TABLE RECEITA (ID INT PRIMARY KEY AUTO_INCREMENT, 
                      DATA_RECEITA DATE,
                      VALOR NUMBER,
                      MODO_PAGAMENTO INT NOT NULL,
                      ID_USUARIO INT NOT NULL,
                      CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID))
CREATE TABLE TIPO_DESPESA (ID INT PRIMARY KEY AUTO_INCREMENT, DESCRICAO VARCHAR(100), CATEGORIA INT)

ENUM MODO_PAGAMENTO {
    1: Dinheiro,
    2: Crédito,
    3: Débito,
    4: Cheque
}